[project]
name = "stLENS"
version = "0.1.0.dev8"
requires-python = ">=3.10"

 
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"stLENS" = ["*.so"]
